version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: iis-projekt
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: iis-projekt
      DB_USERNAME: admin
      DB_PASSWORD: password
  mysql:
    build: db/.
    image: mysql:5.7
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: iis-projekt
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: --init-file /db.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
